version: '2.1'
services:
    postgres:
        image: postgres:9.6
        env_file:
            - .env
        ports:
            - "5432:5432"

    webserver:
        build: .
        image: asatrya/docker-airflow:1.10.6
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        environment: 
            EXECUTOR: "LocalExecutor"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
